version: '3.8'
services:
 app-redis1:
  build: .
  image: redis-rick-and-moryt:1.1.2
  ports:
   - 3000:3000
  environment:
   - .env
 balancer:
  image: nginx 
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
   - 80:80
  depends_on:
   - app-redis1